"""contrasenasi

Revision ID: be1841b7df2c
Revises: b92ea55992f5
Create Date: 2024-11-20 23:45:24.155320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be1841b7df2c'
down_revision: Union[str, None] = 'b92ea55992f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_users', sa.Column('previous_passwords', postgresql.ARRAY(sa.String()), nullable=False, server_default='{}'))
    op.drop_column('accounts_users', 'password_history')
    # ### end Alembic commands ###
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts_users', sa.Column('password_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('accounts_users', 'previous_passwords')
    # ### end Alembic commands ###