"""Init

Revision ID: 2ca0c7119d91
Revises:
Create Date: 2024-10-29 10:16:42.541965

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ca0c7119d91"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts_users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_users_email"), "accounts_users", ["email"], unique=True)
    op.create_index(op.f("ix_accounts_users_username"), "accounts_users", ["username"], unique=True)
    op.create_table(
        "expenses_expenses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("datetime", sa.DateTime(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["accounts_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expenses_debts",
        sa.Column("expense_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("paid_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["expense_id"],
            ["expenses_expenses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["accounts_users.id"],
        ),
        sa.PrimaryKeyConstraint("expense_id", "user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("expenses_debts")
    op.drop_table("expenses_expenses")
    op.drop_index(op.f("ix_accounts_users_username"), table_name="accounts_users")
    op.drop_index(op.f("ix_accounts_users_email"), table_name="accounts_users")
    op.drop_table("accounts_users")
    # ### end Alembic commands ###
